import ChatListSearch from './ChatListSearch.vue';
import ChatList from './ChatList.vue';
import ChatDialogHeader from './ChatDialogHeader.vue';
import ChatDialogMessages from './ChatDialogMessages.vue';
import ChatInput from './ChatInput.vue';
import ChatMessageImage from './ChatMessageImage.vue';
import ChatMessageVoice from './ChatMessageVoice.vue';
import ChatModalImage from './ChatModalImage.vue';
import ChatGroupAddUser from './ChatGroupAddUser.vue';
import ChatGroupInfo from './ChatGroupInfo.vue';
import ChatGroupCreate from './ChatGroupCreate.vue';
import ChatGroupSettings from './ChatGroupSettings.vue';
import ChatMessage from './ChatMessage.vue';
import ChatLayout from './ChatLayout.vue';
import ChatLeftMenu from './ChatLeftMenu.vue';
import ChatGroupUpdate from './ChatGroupUpdate.vue';
import ChatGroupRoles from './ChatGroupRoles.vue';

export const Layout = ChatLayout;
export const List = ChatList;
export const ListSearch = ChatListSearch;
export const DialogHeader = ChatDialogHeader;
export const Messages = ChatDialogMessages;
export const Input = ChatInput;
export const LeftMenu = ChatLeftMenu;
export const GroupCreate = ChatGroupCreate;
export const GroupInfo = ChatGroupInfo;
export const GroupSettings = ChatGroupSettings;
export const GroupAddUser = ChatGroupAddUser;
export const GroupUpdate = ChatGroupUpdate;
export const GroupRoles = ChatGroupRoles;
export const Message = ChatMessage;
export const MessageImage = ChatMessageImage;
export const MessageVoice = ChatMessageVoice;
export const ModalImage = ChatModalImage;
